let
    Source = AzureStorage.DataLake("https://tgbedpprdneusa01.dfs.core.windows.net/databricks/prod/curated/powerbisources/consumerone/omnichannel/dim/VehicleDerivative"),
    #"Filtered Rows" = Table.SelectRows(Source, each ([Extension] = ".parquet")),
    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (10)", each #"Transform File (10)"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (10)"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (10)", Table.ColumnNames(#"Transform File (10)"(#"Sample File (10)"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"VehicleDerivativeWkey", Int64.Type}, {"Manufacturer", type text}, {"LocalModelCode", type text}, {"Derivative", type text}, {"Range", type text}, {"BodyType", type text}, {"BodyStyle", type text}}),
    #"Filtered Rows1" = Table.SelectRows(#"Changed Type", each ([Manufacturer] = "Lexus" or [Manufacturer] = "Toyota")),
    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows1", {"LocalModelCode"}, TransactionsDistinct, {"o_LocalModelCode"}, "TransactionsDistinct", JoinKind.Inner)
in
    #"Merged Queries"
