let
    Source = AzureStorage.DataLake("https://companyedpprdneusa01.dfs.core.windows.net/databricks/prod/curated/powerbisources/consumerone/omnichannel/lmh/signuplead"),
    #"Filtered Rows" = Table.SelectRows(Source, each ([Extension] = ".parquet")),
    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (13)", each #"Transform File (13)"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (13)"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (13)", Table.ColumnNames(#"Transform File (13)"(#"Sample File (13)"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"EmailId", type text}, {"MinDateCreated", type date}, {"MaxDateCreated", type date}, {"l_OriginalRequestTimestamp", type datetime}, {"l_VchLeadTypeDescription", type text}, {"l_VchDealerCode", Int64.Type}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Source.Name"})
in
    #"Removed Columns"
