let
    Source = Excel.Workbook(File.Contents("C:\\Users\\alast\\OneDrive\\Documents\\Work\\Powerforce Task\\Data Set\\D&I Manager Recruitment Task.xlsx"), null, true),
    #"Global retail _Sheet" = Source{[Item="Global retail ",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(#"Global retail _Sheet", [PromoteAllScalars=true]),
    #"Selected Columns" = Table.SelectColumns(#"Promoted Headers", {"Product_Category", "Product_Brand", "Product_Type", "products"}),
    #"Fixed Category" = Table.ReplaceValue(
        #"Selected Columns",
        each [Product_Category],
        each if [Product_Category] = null or [Product_Category] = "" then
            if [products] = "Biography" then "Books"
            else if [products] = "Blazer" then "Clothing"
            else if [products] = "Chocolate-covered fruits" then "Grocery"
            else if [products] = "Chocolate-covered nuts" then "Grocery"
            else if [products] = "Distilled water" then "Grocery"
            else if [products] = "Flip flops" then "Clothing"
            else if [products] = "Self-help" then "Books"
            else if [products] = "Sheath dress" then "Clothing"
            else if [products] = "Smart TV" then "Electronics"
            else if [products] = "Soap dispenser" then "Home Decor"
            else if [products] = "Sony Xperia Tablet" then "Electronics"
            else if [products] = "TV stand" then "Home Decor"
            else if [products] = "Wall art" then "Home Decor"
            else if [products] = "White chocolate" then "Grocery"
            else [Product_Category]
        else [Product_Category],
        Replacer.ReplaceValue,
        {"Product_Category"}
    ),
    #"Removed Duplicates" = Table.Distinct(#"Fixed Category", {"Product_Category", "Product_Brand", "Product_Type", "products"}),
    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Product_ID", 1, 1, Int64.Type),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Index", {"Product_ID", "Product_Category", "Product_Brand", "Product_Type", "products"})
in
    #"Reordered Columns"
