USE GAME_ARC
GO

--------------------------------------------PRODUCT TABLE----------------------------------------
-------------------------------------------------------------------------------------------------

IF OBJECT_ID ('tempdb..#LEGO') IS NOT NULL
	DROP TABLE #LEGO

SELECT *
	INTO #LEGO
	FROM DIM_PRODUCT P (NOLOCK)
	WHERE P.MANUFACTURE_CODE = 500687
		AND P.PROD_TYPE_CODE = '425'
		AND P.SUBCLASS_CODE = 'TBB'
		AND P.MERCHANDISE_FLG = 'YES'
GO

--SELECT * FROM #LEGO

---------------------------------------FACT SALES TABLE------------------------------------------
-------------------------------------------------------------------------------------------------

IF OBJECT_ID ('tempdb..#BSKT') IS NOT NULL
	DROP TABLE #BSKT

SELECT FCT.*
	INTO #BSKT
	FROM (
			SELECT * FROM FCT_SALES_LINES (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_LINES_2020_Q2 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_LINES_2020_Q1 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_LINES_2019_Q3 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_LINES_2019_Q2 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_LINES_2019_Q1 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_LINES_2018_Q4 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_LINES_2018_Q3 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_LINES_2018_Q2 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_LINES_2018_Q1 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_LINES_2017_Q4 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_LINES_2017_Q3 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_LINES_2017_Q2 (NOLOCK)
		) FCT
		INNER JOIN #LEGO P ON P.PRODUCT_KEY = FCT.PRODUCT_KEY
		INNER JOIN DIM_DATE D (NOLOCK) ON D.DATE_KEY = FCT.DATE_KEY
	WHERE
		D.DATE_FLD >= '2018-01-01' AND D.DATE_FLD < '2024-01-01'
		AND SALE_INVC_TYPE IN ('REG-INV','DISC-SALE')
GO

---------------------------------------FACT DETAIL TABLE------------------------------------------
--------------------------------------------------------------------------------------------------

IF OBJECT_ID ('tempdb..#RBSKT') IS NOT NULL
	DROP TABLE #RBSKT

SELECT FH.*
	INTO #RBSKT
	FROM (
			SELECT * FROM FCT_SALES_HEADER (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_HEADER_2020_Q2 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_HEADER_2020_Q1 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_HEADER_2019_Q3 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_HEADER_2019_Q2 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_HEADER_2019_Q1 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_HEADER_2018_Q4 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_HEADER_2018_Q3 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_HEADER_2018_Q2 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_HEADER_2018_Q1 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_HEADER_2017_Q4 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_HEADER_2017_Q3 (NOLOCK)
			UNION ALL
			SELECT * FROM FCT_SALES_HEADER_2017_Q2 (NOLOCK)
		) FH
		INNER JOIN DIM_DATE D (NOLOCK) ON D.DATE_KEY = FH.DATE_KEY
		INNER JOIN #BSKT B (NOLOCK) ON B.INVOICE_NO = FH.INVOICE_NO
	WHERE
		D.DATE_FLD >= '2018-01-01' AND D.DATE_FLD < '2024-01-01'
GO

---------------------------------------DATA PULLS------------------------------------------
--------------------------------------------------------------------------------------------------

SELECT	DATEPART(YEAR,D.DATE_FLD) 'Year',
		COUNT(DISTINCT B.INVOICE_NO) 'BSKT'
	FROM #BSKT B
		INNER JOIN DIM_DATE D (NOLOCK) ON D.DATE_KEY = B.DATE_KEY
	GROUP BY
		DATEPART(YEAR,D.DATE_FLD)
	ORDER BY
		[Year]
GO

SELECT	DATEPART(YEAR,D.DATE_FLD) 'Year',
		COUNT(DISTINCT RB.INVOICE_NO) 'RWD_BSKT'
	FROM #RBSKT RB
		INNER JOIN DIM_DATE D (NOLOCK) ON D.DATE_KEY = RB.DATE_KEY
	WHERE
		RB.CUSTOMER_CODE <>'UK - 99999'
	GROUP BY
		DATEPART(YEAR,D.DATE_FLD)
	ORDER BY
		[Year]
GO